Project2WooxTravel/Areas/Admin/Controllers/AdmninLayoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project2WooxTravel.Areas.Admin.Controllers
{
    public class AdmninLayoutController : Controller
    {
        // GET: Admin/AdmninLayout
        public ActionResult Index()
        {
            return View();
        }
        public PartialViewResult PartialHead()
        {
            return PartialView();
        }
        public PartialViewResult PartialSidebar()
        {
            return PartialView();
        }
        public PartialViewResult PartialNavbar()
        {
            return PartialView();
        }
        public PartialViewResult PartialFooter()
        {
            return PartialView();
        }
        public PartialViewResult PartialScript()
        {
            return PartialView();
        }
        public PartialViewResult PartialNavbarMessage()
        {
            return PartialView();   
        }
    }
}

Project2WooxTravel/Areas/Admin/Views/AdmninLayout/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
@Html.Action("PartialHead", "AdmninLayout", "Admin")
<body>
    <div class="wrapper">

        @Html.Action("PartialSidebar", "AdmninLayout", "Admin")

        @Html.Action("PartialNavbar", "AdmninLayout", "Admin")

        @RenderBody()

        @Html.Action("PartialFooter", "AdmninLayout", "Admin")

    </div>

    @Html.Action("PartialScript", "AdmninLayout", "Admin")

</body>
</html>

Project2WooxTravel/Areas/Admin/Views/AdmninLayout/PartialFooter.cshtml
<footer class="footer">
    <div class="container-fluid d-flex justify-content-between">
        <nav class="pull-left">
            <ul class="nav">
                <li class="nav-item">
                    <a class="nav-link" href="http://www.themekita.com">
                        ThemeKita
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#"> Yardım </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#"> Lisanslar </a>
                </li>
            </ul>
        </nav>
        <div class="copyright">
            <i class="fa fa-heart heart text-danger"></i>
            <a href="http://www.themekita.com">Thene Kita</a>
             Tarfından Yapıldı
        </div>
        <div>
            <a target="_blank" href="https://themewagon.com/">#</a>
        </div>
    </div>
</footer>

Project2WooxTravel/Areas/Admin/Views/AdmninLayout/PartialHead.cshtml
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>Woox Travel Admin Paneli</title>
    <meta content="width=device-width, initial-scale=1.0, shrink-to-fit=no"
          name="viewport" />
    <link rel="icon"
          href="/kaiadmin-lite-1.2.0/assets/img/kaiadmin/favicon.ico"
          type="image/x-icon" />

    <!-- Fonts and icons -->
    <script src="/kaiadmin-lite-1.2.0/assets/js/plugin/webfont/webfont.min.js"></script>
    <script>
WebFont.load({
        google: { families: ["Public Sans:300,400,500,600,700"] },
        custom: {
          families: [
            "Font Awesome 5 Solid",
            "Font Awesome 5 Regular",
            "Font Awesome 5 Brands",
            "simple-line-icons",
          ],
            urls: ["/kaiadmin-lite-1.2.0/assets/css/fonts.min.css"],
        },
        active: function () {
          sessionStorage.fonts = true;
        },
      });</script>

    <!-- CSS Files -->
    <link rel="stylesheet" href="/kaiadmin-lite-1.2.0/assets/css/bootstrap.min.css" />
    <link rel="stylesheet" href="/kaiadmin-lite-1.2.0/assets/css/plugins.min.css" />
    <link rel="stylesheet" href="/kaiadmin-lite-1.2.0/assets/css/kaiadmin.min.css" />

    <!-- CSS Just for demo purpose, don't include it in your project -->
    <link rel="stylesheet" href="/kaiadmin-lite-1.2.0/assets/css/demo.css" />
</head>

Project2WooxTravel/Areas/Admin/Views/AdmninLayout/PartialScript.cshtml
<script src="/kaiadmin-lite-1.2.0/assets/js/core/jquery-3.7.1.min.js"></script>
<script src="/kaiadmin-lite-1.2.0/assets/js/core/popper.min.js"></script>
<script src="/kaiadmin-lite-1.2.0/assets/js/core/bootstrap.min.js"></script>

<!-- jQuery Scrollbar -->
<script src="/kaiadmin-lite-1.2.0/assets/js/plugin/jquery-scrollbar/jquery.scrollbar.min.js"></script>
<!-- Kaiadmin JS -->
<script src="/kaiadmin-lite-1.2.0/assets/js/kaiadmin.min.js"></script>
<!-- Kaiadmin DEMO methods, don't include it in your project! -->
<script src="/kaiadmin-lite-1.2.0/assets/js/setting-demo2.js"></script>
<script>
$("#displayNotif").on("click", function () {
        var placementFrom = $("#notify_placement_from option:selected").val();
        var placementAlign = $("#notify_placement_align option:selected").val();
        var state = $("#notify_state option:selected").val();
        var style = $("#notify_style option:selected").val();
        var content = {};

        content.message =
          'Turning standard Bootstrap alerts into "notify" like notifications';
        content.title = "Bootstrap notify";
        if (style == "withicon") {
          content.icon = "fa fa-bell";
        } else {
          content.icon = "none";
        }
        content.url = "index.html";
        content.target = "_blank";

        $.notify(content, {
          type: state,
          placement: {
            from: placementFrom,
            align: placementAlign,
          },
          time: 1000,
        });
      });</script>

Project2WooxTravel/Areas/Admin/Views/AdmninLayout/PartialSidebar.cshtml
<div class="sidebar" data-background-color="dark">
    <div class="sidebar-logo">
        <!-- Logo Header -->
        <div class="logo-header" data-background-color="dark">
            <a href="/kaiadmin-lite-1.2.0/index.html" class="logo">
                <img src="/kaiadmin-lite-1.2.0/assets/img/kaiadmin/logo_light.svg"
                     alt="navbar brand"
                     class="navbar-brand"
                     height="20" />
            </a>
            <div class="nav-toggle">
                <button class="btn btn-toggle toggle-sidebar">
                    <i class="gg-menu-right"></i>
                </button>
                <button class="btn btn-toggle sidenav-toggler">
                    <i class="gg-menu-left"></i>
                </button>
            </div>
            <button class="topbar-toggler more">
                <i class="gg-more-vertical-alt"></i>
            </button>
        </div>
        <!-- End Logo Header -->
    </div>
    <div class="sidebar-wrapper scrollbar scrollbar-inner">
        <div class="sidebar-content">
            <ul class="nav nav-secondary">
                <li class="nav-item">
                    <a data-bs-toggle="collapse"
                       href="#dashboard"
                       class="collapsed"
                       aria-expanded="false">
                        <i class="fas fa-home"></i>
                        <p>Dashboard</p>
                        <span class="caret"></span>
                    </a>
                    <div class="collapse" id="dashboard">
                        <ul class="nav nav-collapse">
                            <li>
                                <a href="../../demo1/index.html">
                                    <span class="sub-item">Dashboard 1</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
                <li class="nav-section">
                    <span class="sidebar-mini-icon">
                        <i class="fa fa-ellipsis-h"></i>
                    </span>
                    <h4 class="text-section">Components</h4>
                </li>
                <li class="nav-item" id="categoryWoox">
                    <a href="@Url.Action("CategoryList","Category")">
                        <i class="fas fa-layer-group"></i>
                        <p>Kategori İşlemleri</p>
                    </a>
                </li>
                <li class="nav-item" id="destinationWoox">
                    <a href="@Url.Action("DestinationList","Destination")">
                        <i class="fas fa-layer-group"></i>
                        <p>Destinasyon İşlemleri</p>
                    </a>
                </li>
                <li class="nav-item" id="inboxWoox">
                    <a href="@Url.Action("Inbox","Message")">
                        <i class="fas fa-layer-group"></i>
                        <p>Mesaj İşlemleri</p>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>